Ejercicio 2.2
profedotc/cristina_guerra pull request #3
Opened 2019-05-29 18:03 UTC by crissty

Pull request ejercicio 2.2

2019-06-01 17:59 UTC, profedotc requested changes
Has movido bien el código, pero quiero que tengáis 3 archivos:
* `main.c`
* `gol.h`
* `gol.c`

La idea es que tu `gol.h` y `gol.c` sean la declaración y definición del juego de la vida. En el `main.c` sólo debe quedar un `#include "gol.h"` y la función `main()`

2019-06-01 17:59 UTC, profedotc commented on makefile
> +gol.o: gol.c
`gol.o` también depende de `gol.h`

2019-06-03 15:05 UTC, crissty commented on makefile
> +gol.o: gol.c
Es verdad, se me ha pasado. Subido commit

2019-06-03 15:06 UTC, crissty commented
Commit añadido con los arreglos.

2019-06-04 18:47 UTC, profedotc commented
Perfecto

2019-06-04 18:47 UTC, merged