Tarea 5.1
profedotc/cristina_guerra pull request #8
Opened 2019-07-01 20:10 UTC by crissty

Implementar test de memoria

2019-07-01 23:13 UTC, profedotc requested changes
has subido el binario `main_test`, bórralo del repo y añádelo a tu `.gitignore`

2019-07-01 23:13 UTC, profedotc commented on main_test.c
> +	bool success = gol_alloc(&gol1, 10, 10);
has la prueba con un mundo rectangular

2019-07-01 23:13 UTC, profedotc commented on makefile
> +.PHONY: main_test
`release`, `debug`, `test`, `all` y `clean` también deberían ir en `.PHONY` porque ningúno está destinado a crear un archivo con ese nombre

2019-07-01 23:13 UTC, profedotc commented on makefile
> +main_test.o: main_test.c gol.o
También depende de `gol.h`

2019-07-01 23:13 UTC, profedotc commented on makefile
> +	$(CC) $(FLAGS) main_test.o gol.o -o main_test
Aquí no tienes que volver a compilar. Make debe recompilar solo si `gol.o` o `main_test.o` cambian

2019-07-03 21:33 UTC, crissty commented
He hecho las modificaciones y eliminado el binario.

2019-07-04 20:58 UTC, merged